# Docker Compose file for Observium on Docker Swarm
# Maintained by somsakc@hotmail.com
# Updated for Docker Swarm with Portainer and persistent volumes

version: '3.8'

services:
  db:
    image: ${MARIADB_IMAGE:-mariadb:11.7}
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_USER=observium
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_DATABASE=observium
      - TZ=Asia/Bangkok
    volumes:
      - observium_data:/var/lib/mysql
    networks:
      - observium_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  app:
    image: ${OBSERVIUM_IMAGE:-mbixtech/observium:24.12}
    environment:
      - OBSERVIUM_ADMIN_USER=admin
      - OBSERVIUM_ADMIN_PASS=passw0rd
      - OBSERVIUM_DB_HOST=db
      - OBSERVIUM_DB_NAME=observium
      - OBSERVIUM_DB_USER=observium
      - OBSERVIUM_DB_PASS=passw0rd
      - OBSERVIUM_BASE_URL=http://app:8888
      - TZ=Asia/Bangkok
    volumes:
      - observium_logs:/opt/observium/logs
      - observium_rrd:/opt/observium/rrd
    networks:
      - observium_network
    ports:
      - "8888:80"
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  observium_network:
    driver: overlay
    attachable: true

volumes:
  observium_data:
    driver: local
  observium_logs:
    driver: local
  observium_rrd:
    driver: local